- attrs: 
    calibration_date: ''
    comment: No NVS Vocabulary as of 2024-09.
    description: Fluorometer (ug/L) and scattering sensor
    factory_calibrated: ''
    long_name: flbbbbV1
    maker: WET Labs, Sea-Bird Scientific
    maker_vocabulary: http://vocab.nerc.ac.uk/collection/L35/current/MAN0026/, http://vocab.nerc.ac.uk/collection/B75/current/ORG00226/
    model: flbbbbV1
    model_vocabulary: ''
    owner: ''
    references: ''
    serial_number: ''
    type: ''
    type_vocabulary: ''
    user_calibrated: ''
  nc_var_name: instrument_flbbbbv1
  type: i4

