- attrs: 
    calibration_date: ''
    comment: 'Model 3830'
    description: A dissolved oxygen sensor designed to mount on RCM 9 or RDCP 600 or similar OEM applications. Measurement based on the ability of selected substances to act as dynamic fluorescence quenchers. The fluorescent indicator is a special platinum porphyrin complex embedded in a gas permeable foil that is exposed to the surrounding water. A black optical isolation coating protects the complex from sunlight and fluorescent particles in the water. This sensing foil is attached to a window providing optical access for the measuring system from inside a watertight titanium housing (depth rating 6000m).The foil is excited by modulated blue light, and the phase of a returned red light is measured. By linearizing and temperature compensating, with an incorporated temperature sensor, the absolute O2 concentration can be determined. Accuracy +/- 5% or 8uM; precision +/- 0.4 uM.
    factory_calibrated: ''
    long_name: AA Optode 3830
    maker: Aanderaa Data Instruments AS
    maker_vocabulary: http://vocab.nerc.ac.uk/collection/B75/current/ORG00228/,http://vocab.nerc.ac.uk/collection/L35/current/MAN0007/
    model: Aanderaa Oxygen Optode 3830
    model_vocabulary: http://vocab.nerc.ac.uk/collection/L22/current/TOOL0836/
    owner: ''
    references: ''
    serial_number: ''
    type: sensor_model,dissolved gas sensors
    type_vocabulary: http://vocab.nerc.ac.uk/collection/L19/current/SDNKG17/,http://vocab.nerc.ac.uk/collection/L05/current/351/
    user_calibrated: ''
  nc_var_name: instrument_optode
  type: i4
