# location of pH calibration .pdf files: /home/coolgroup/Gliders/Glider Payload Sensors/CALIBRATION SHEETS - Seabird CTD & pH
- attrs: 
    calibration_date: ''
    comment: pH sensor
    description: The original design of a deep ISFET (Ion Sensitive Field Effect Transistor) pH sensor (Deep-Sea DuraFET developed by MBARI, Johnson et al 2016) was modified by Sea-Bird Scientific and integrated into a Slocum Webb glider. This pH sensor was reconfigured to fit into an existing glider CTD port utilizing a shared pumped system to pull seawater in past both the pH and CTD sensor elements. The sensor measures pH with a range of 6.5 to 9.0, has an accuracy to +/-0.05 pH units, and precision of 0.001 pH units. It is calibrated in temperatures ranging from 5 deg C to 35 deg C and has a depth rating of 2000 m.
    factory_calibrated: 
    long_name: Deep ISFET Glider-based pH Sensor
    maker: Sea-Bird Scientific
    maker_vocabulary: https://vocab.nerc.ac.uk/collection/B75/current/ORG00226/,https://vocab.nerc.ac.uk/collection/L35/current/MAN0013/
    model: Deep ISFET Glider-based pH Sensor
    model_vocabulary: ''
    owner: ''
    references: Saba et al 2019 https://doi.org/10.3389/fmars.2019.00664,Johnson et al 2016 https://doi.org/10.1021/acs.analchem.5b04653
    serial_number: ''
    type: pH sensors
    type_vocabulary: https://vocab.nerc.ac.uk/collection/L05/current/355/
    user_calibrated: ''
    calibration_coefficients: '{"f1": 9.103373736788e-07, "f2": 9.333124824793e-08, "f3": -3.584728104675e-10, "f4": 6.798524962365e-13, "f5": -7.610036486321e-16, "f6": 5.244183802791e-19, "f7": -2.185931775071e-22, "f8": 5.054983318907e-26, "f9": -4.977018540451e-30, "f10": 0, "f11": 0, "f12": 0, "k0": -1.3029, "k2f0": -0.00088571, "k2f1": 3.2695e-09, "k2f2": -2.4187e-11, "k2f3": 9.8745e-15}'
  nc_var_name: instrument_pH
  type: i4
