- attrs: 
    calibration_date: 2020-08-21
    comment: pH sensor
    description: The original design of a deep ISFET (Ion Sensitive Field Effect Transistor) pH sensor (Deep-Sea DuraFET developed by MBARI, Johnson et al 2016) was modified by Sea-Bird Scientific and integrated into a Slocum Webb glider. This pH sensor was reconfigured to fit into an existing glider CTD port utilizing a shared pumped system to pull seawater in past both the pH and CTD sensor elements. The sensor measures pH with a range of 6.5 to 9.0, has an accuracy to +/-0.05 pH units, and precision of 0.001 pH units. It is calibrated in temperatures ranging from 5 deg C to 35 deg C and has a depth rating of 2000 m.
    factory_calibrated: 2020-08-21
    long_name: Deep ISFET Glider-based pH Sensor
    maker: Sea-Bird Scientific
    maker_vocabulary: https://vocab.nerc.ac.uk/collection/B75/current/ORG00226/,https://vocab.nerc.ac.uk/collection/L35/current/MAN0013/
    model: Deep ISFET Glider-based pH Sensor
    model_vocabulary: ''
    owner: University of Maine
    references: Saba et al 2019 https://doi.org/10.3389/fmars.2019.00664,Johnson et al 2016 https://doi.org/10.1021/acs.analchem.5b04653
    serial_number: '10490'
    type: pH sensors
    type_vocabulary: https://vocab.nerc.ac.uk/collection/L05/current/355/
    user_calibrated: ''
    calibration_coefficients: '{"f1": 1.6573e-05, "f2": -2.6822e-08, "f3": 2.5197e-11, "f4": -1.338e-14, "f5": 3.8234e-18, "f6": -4.584e-22, "k0": -1.419355, "k2": -0.0010291}'
  nc_var_name: instrument_pH
  type: i4
