- attrs: 
    calibration_date: 1970-01-01
    comment: No calibration date. No NVS vocabulary for instrument as of 2023-04-20. VMT transmits with ID 24357.
    description: The Vemco Mobile Transceiver (VMT) is a hybrid between a 69 kHz coded transmitter and a 69 kHz monitoring receiver (similar to the VR2W-69 kHz). The VMT is externally attached to an animal or glider and its receiving capabilities enable it to detect other animals that have been tagged with a 69 kHz coded transmitter. Coded transmitting capabilities also allow the VMT to be detected by other deployed 69 kHz receivers. The VMT comes with several user programmable options such as the ability to vary receiver ON time (duty cycle), as well as some tag programming options. Depth rated to 1000 m.
    factory_calibrated: 1970-01-01
    long_name: Vemco Mobile Transceiver (VMT)
    maker: Innovasea Systems Inc.,VEMCO
    maker_vocabulary: http://vocab.nerc.ac.uk/collection/L35/current/MAN0207/,http://vocab.nerc.ac.uk/collection/B75/current/ORG00348/
    model: VMT
    model_vocabulary: ''
    owner: Teledyne Webb Research
    references: https://www.innovasea.com/wp-content/uploads/2021/06/Innovasea-Fish-Tracking-vmt-data-sheet-0621.pdf
    serial_number: '1196240'
    type: tracking tags
    type_vocabulary: http://vocab.nerc.ac.uk/collection/L05/current/TRTG/
    user_calibrated: ''
  nc_var_name: instrument_vmt
  type: i4
