- attrs: 
    calibration_date: 2024-06-11
    comment: This pH sensor is integrated with Sea-Bird GPCTD serial number 9916
    description: The original design of a deep ISFET (Ion Sensitive Field Effect Transistor) pH sensor (Deep-Sea DuraFET developed by MBARI, Johnson et al 2016) was modified by Sea-Bird Scientific and integrated into a Slocum Webb glider. This pH sensor was reconfigured to fit into an existing glider CTD port utilizing a shared pumped system to pull seawater in past both the pH and CTD sensor elements. The sensor measures pH with a range of 6.5 to 9.0, has an accuracy to +/-0.05 pH units, and precision of 0.001 pH units. It is calibrated in temperatures ranging from 5 deg C to 35 deg C and has a depth rating of 2000 m.
    factory_calibrated: 2024-06-11
    long_name: Deep ISFET Glider-based pH Sensor
    make_model: Sea-Bird Deep ISFET Glider-based pH Sensor
    maker: Sea-Bird Scientific
    maker_vocabulary: https://vocab.nerc.ac.uk/collection/B75/current/ORG00226/,https://vocab.nerc.ac.uk/collection/L35/current/MAN0013/
    model: Deep ISFET Glider-based pH Sensor
    model_vocabulary: ''
    owner: Rutgers University
    references: Saba et al 2019 https://doi.org/10.3389/fmars.2019.00664,Johnson et al 2016 https://doi.org/10.1021/acs.analchem.5b04653
    serial_number: '12111'
    type: pH sensors
    type_vocabulary: https://vocab.nerc.ac.uk/collection/L05/current/355/
    user_calibrated: ''
    calibration_coefficients: '{"f1": 0.000009092056812525, "f2": 2.367514411577e-08, "f3": -1.289327778908e-10, "f4": 2.69055979149e-13, "f5": -3.184217390153e-16, "f6": 2.290504460079e-19, "f7": -9.895342051846e-23, "f8": 2.358877646314e-26, "f9": -2.383449353933e-30, "f10": 0, "f11": 0, "f12": 0, "k0": -1.312924446, "k2f0": -8.7852e-04, "k2f1": -4.4349e-08, "k2f2": 2.7615e-11, "k2f3": -6.2765e-15}'
  nc_var_name: instrument_pH
  type: i4
- attrs: 
    calibration_date: 2022-10-21
    comment: This pH sensor is integrated with Sea-Bird GPCTD serial number 9916
    description: The original design of a deep ISFET (Ion Sensitive Field Effect Transistor) pH sensor (Deep-Sea DuraFET developed by MBARI, Johnson et al 2016) was modified by Sea-Bird Scientific and integrated into a Slocum Webb glider. This pH sensor was reconfigured to fit into an existing glider CTD port utilizing a shared pumped system to pull seawater in past both the pH and CTD sensor elements. The sensor measures pH with a range of 6.5 to 9.0, has an accuracy to +/-0.05 pH units, and precision of 0.001 pH units. It is calibrated in temperatures ranging from 5 deg C to 35 deg C and has a depth rating of 2000 m.
    factory_calibrated: 2022-10-21
    long_name: Deep ISFET Glider-based pH Sensor
    make_model: Sea-Bird Deep ISFET Glider-based pH Sensor
    maker: Sea-Bird Scientific
    maker_vocabulary: https://vocab.nerc.ac.uk/collection/B75/current/ORG00226/,https://vocab.nerc.ac.uk/collection/L35/current/MAN0013/
    model: Deep ISFET Glider-based pH Sensor
    model_vocabulary: ''
    owner: Rutgers University
    references: Saba et al 2019 https://doi.org/10.3389/fmars.2019.00664,Johnson et al 2016 https://doi.org/10.1021/acs.analchem.5b04653
    serial_number: '12111'
    type: pH sensors
    type_vocabulary: https://vocab.nerc.ac.uk/collection/L05/current/355/
    user_calibrated: ''
    calibration_coefficients: '{"f1": 0.000009092056812525, "f2": 2.367514411577e-08, "f3": -1.289327778908e-10, "f4": 2.69055979149e-13, "f5": -3.184217390153e-16, "f6": 2.290504460079e-19, "f7": -9.895342051846e-23, "f8": 2.358877646314e-26, "f9": -2.383449353933e-30, "f10": 0, "f11": 0, "f12": 0, "k0": -1.308224882, "k2f0": -8.7852e-04, "k2f1": -4.4349e-08, "k2f2": 2.7615e-11, "k2f3": -6.2765e-15}'
  nc_var_name: instrument_pH
  type: i4
