- attrs: 
    calibration_date: 2022-11-08
    comment: pH sensor
    description: The original design of a deep ISFET (Ion Sensitive Field Effect Transistor) pH sensor (Deep-Sea DuraFET developed by MBARI, Johnson et al 2016) was modified by Sea-Bird Scientific and integrated into a Slocum Webb glider. This pH sensor was reconfigured to fit into an existing glider CTD port utilizing a shared pumped system to pull seawater in past both the pH and CTD sensor elements. The sensor measures pH with a range of 6.5 to 9.0, has an accuracy to +/-0.05 pH units, and precision of 0.001 pH units. It is calibrated in temperatures ranging from 5 deg C to 35 deg C and has a depth rating of 2000 m.
    factory_calibrated: 2022-11-08
    long_name: Deep ISFET Glider-based pH Sensor
    maker: Sea-Bird Scientific
    maker_vocabulary: https://vocab.nerc.ac.uk/collection/B75/current/ORG00226/,https://vocab.nerc.ac.uk/collection/L35/current/MAN0013/
    model: Deep ISFET Glider-based pH Sensor
    model_vocabulary: ''
    owner: Rutgers University
    references: Saba et al 2019 https://doi.org/10.3389/fmars.2019.00664,Johnson et al 2016 https://doi.org/10.1021/acs.analchem.5b04653
    serial_number: '12177'
    type: pH sensors
    type_vocabulary: https://vocab.nerc.ac.uk/collection/L05/current/355/
    user_calibrated: ''
    calibration_coefficients: '{"f1": 0.000009636517271864, "f2": 4.594458044384e-08, "f3": -2.171759626988e-10, "f4": 4.213316837342e-13, "f5": -4.642088344705e-16, "f6": 3.110177402035e-19, "f7": -1.256290707573e-22, "f8": 2.816999264651e-26, "f9": -2.695541321192e-30, "f10": 0, "f11": 0, "f12": 0, "k0": -1.3292, "k2f0": -8.6158e-04, "k2f1": -5.3435e-08, "k2f2": 4.0796e-11, "k2f3": -1.0982e-14}'
  nc_var_name: instrument_pH
  type: i4
