- attrs: 
    calibration_date: 2012-08-20
    comment: Chlorophyll a,beta700nm,CDOM
    description: A variant of the ECO Puck Triplet (http://vocab.nerc.ac.uk/collection/L22/current/TOOL0673/). It is a three-optical-sensor, user-defined instrument that carries a chlorophyll-a fluorometer, FDOM fluorometer and scattering meter. ECO Pucks are real-time only sensors as they are integrated onto the OEM platform that provides power and data handling. The SLK designation signifies this is a second generation model that is specific for integration into Slocum gliders. The fluorometers and scattering meter are single wavelength sensors. The model is depth-rated to 1000 m.
    factory_calibrated: 2012-08-20
    long_name: WETLabs ECO FLBBCD-SLK
    maker: WET Labs,Sea-Bird Scientific
    maker_vocabulary: http://vocab.nerc.ac.uk/collection/L35/current/MAN0026/,http://vocab.nerc.ac.uk/collection/B75/current/ORG00226/
    model: WETLabs ECO Puck Triplet FLBBCD-SLK scattering fluorescence sensor
    model_vocabulary: https://vocab.nerc.ac.uk/collection/L22/current/TOOL1313/
    owner: Rutgers University
    references: ''
    serial_number: '2797'
    type: sensor_model,fluorometer,optical backscatter sensor
    type_vocabulary: http://vocab.nerc.ac.uk/collection/L19/current/SDNKG17/,http://vocab.nerc.ac.uk/collection/L05/current/113/,http://vocab.nerc.ac.uk/collection/L05/current/123/
    user_calibrated: ''
  nc_var_name: instrument_flbbcdslk
  type: i4
