- attrs: 
    calibration_date: 2003-02-05
    comment: Unpumped
    description: A self-contained unpumped unit comprising the temperature, conductivity and pressure sensors that is designed specifically for deployment on ocean gliders. The sensors are typically installed externally on the hull of the glider. These are OEM products with variable specifications; they are calibrated in a calibration fixture at Sea-Bird, removed from that fixture, and installed in a housing that Sea-Bird does not know or have control over. Additionally, sensor performance is dependent on flow rate through the cell and water column temperature and salinity gradients.
    factory_calibrated: 2003-02-05
    long_name: SBE CT Sail
    maker: Sea-Bird Scientific
    maker_vocabulary: https://vocab.nerc.ac.uk/collection/L35/current/MAN0013/,https://vocab.nerc.ac.uk/collection/B75/current/ORG00226/
    model: Sea-Bird CT Sail CTD
    model_vocabulary: https://vocab.nerc.ac.uk/collection/L22/current/TOOL1188/
    owner: Rutgers University
    serial_number: '34'
    type: CTD,salinity sensor,sensor model,water temperature sensor
    type_vocabulary: http://vocab.nerc.ac.uk/collection/L05/current/130/,http://vocab.nerc.ac.uk/collection/L05/current/350/,http://vocab.nerc.ac.uk/collection/L19/current/SDNKG17/,http://vocab.nerc.ac.uk/collection/L05/current/134/
    user_calibrated: ''
  nc_var_name: instrument_ctd
  type: i4
