- attrs: 
    calibration_date: 2009-11-03
    comment: beta470nm,bb532nm,Chlorophyll a
    description: A variant of the ECO Puck Triplet (http://vocab.nerc.ac.uk/collection/L22/current/TOOL0673/). It is a three-optical-sensor, user-defined instrument that carries a fluorometer and 2 scattering meters. ECO Pucks are real‐time only sensors as they are integrated onto the OEM platform that provides power and data handling. The SLC designation signifies this is a third generation model that is specific for integration into Slocum gliders with a dry science bay. The fluorometer and scattering meters are single wavelength sensors. The model is fitted with an added copper faceplate for bio-fouling mitigation and is depth-rated to 1000 m.
    factory_calibrated: 2009-11-03
    long_name: WET Labs ECO BB2FL-SLC
    maker: Sea-Bird Scientific,WET Labs
    maker_vocabulary: https://vocab.nerc.ac.uk/collection/B75/current/ORG00226/,https://vocab.nerc.ac.uk/collection/L35/current/MAN0026/
    model: WET Labs {Sea-Bird WETLabs} ECO Puck Triplet BB2FL-SLC scattering fluorescence sensor
    model_vocabulary: https://vocab.nerc.ac.uk/collection/L22/current/TOOL1316/
    owner: Rutgers University
    references: ''
    serial_number: '696'
    type: sensor_model, optical backscatter sensor
    type_vocabulary: http://vocab.nerc.ac.uk/collection/L05/current/123/,https://vocab.nerc.ac.uk/collection/L19/current/SDNKG17/
    user_calibrated: ''
  nc_var_name: instrument_bbfl2slc
  type: i4
